### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by effzeh972** [Kleinrotti/hass-senertec#1]
Hi, getting this Error when I try to configurate the Integration:

"Fehler
Diese Integration unterstützt keine Konfiguration über die Benutzeroberfläche. Wenn du diesem Link von der Home Assistant-Website gefolgt bist, stelle sicher, dass du die neueste Version von Home Assistant ausführst."

Newest HomAssistant ver. is installed, also tried to restart it a few times didn´t help either.  :

[config-flow.txt](https://github.com/Kleinrotti/hass-senertec/files/9096787/config-flow.txt)
[loading-configuration.txt](https://github.com/Kleinrotti/hass-senertec/files/9096789/loading-configuration.txt)

**Comment by Kleinrotti** [comment]
Please append the log messages from hass-senertec for further investigation.

**Comment by Kleinrotti** [comment]
I found the issue. This should be fixed in v.0.1.3.

**Comment by effzeh972** [comment]
Awesome, works now.
