### ISSUE TITLE
Die Zustände der Anlage als Status in HA hinterlegen

### ISSUE THREAD

**Issue by MarAlze** [Kleinrotti/hass-senertec#2]
Die Zustände Anlage als Status in HA hinterlegen, dass der Verlauf auch geloggt wird.
Z. B. beim Spitzenlastkessel Standby und Erzeugung oder bei der Brennstoffzelle, Erzeugung, Aufwärmen etc. 

Mein Python ist leider noch immer nicht gut genug, um etwas Passendes vorzubereiten.

Hier eine Beispielanpassung aus meiner configuration.yaml
sensor:
  - platform: template
    sensors:
      Xxxxx_brennstoffzelle_status:
        value_template: "{{states('sensor.xxxxx_status_of_ppc')}}"
        unique_id: sensor.xxxxx_brennstoffzelle_status

Über diesen Weg habe ich alle "Textsensoren" um ein Logging erweitert.

PS. Gäbe es noch eine Möglichkeit, die 3 Speicher Temperaturen auszulesen?

https://www.home-assistant.io/docs/configuration/state_object
https://www.home-assistant.io/docs/configuration/templating/

**Comment by Kleinrotti** [comment]
Meinst du sowas als Verlauf?
![image](https://user-images.githubusercontent.com/39203164/224482018-92de95fe-970f-408a-81bb-09e0bff953b3.png)

**Comment by MarAlze** [comment]
Ja genau. Wenn es so implementiert ist wird es sogar im Logbuch angezeigt. 
Bei bei meiner aktuell nicht. Aber es wird halt aufgezeichnet und dargestellt.


Bei "AI-on-the-edge-device" wird es unter diagnostic abgelegt was auch ein interessanter weg wäre:
z.B. Zeile 171 in der automatischen mqtt Erkennung 
https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/code/components/jomjol_mqtt/server_mqtt.cpp
![Screenshot_20230311-130608](https://user-images.githubusercontent.com/96615259/224483445-350e1b27-d6f2-4194-8f3c-03361ad9661f.png)


Bei mir sieht es so aus:
![Screenshot_20230311-125313~2](https://user-images.githubusercontent.com/96615259/224482915-d7a411bc-bb26-4edb-b42d-bf9eda529b24.png)

**Comment by Kleinrotti** [comment]
Okay ich verstehe. Sollte kein Problem sein.
Schau ich mir an.

Zu deiner Sensor Frage, ich bin aktuell an einem größeren Update dran wo man im Homeassistant dann aus allen verfügbaren Sensoren die passenden Auswählen kann, die man drin haben möchte. In der py-senertec Python Bibliothek habe ich das schon implementiert. Bin noch dran das auch in der Homeassistant Integration ein zu bauen. Ist nur etwas tricky, da z. B. bei dem Senertec Dachs2 über 400 Sensorwerte vorhanden sind und ich mir noch überlegen muss wie ich das darstelle ohne den Nutzer mit Sensoren zu "fluten" die sowieso unnötig sind und dadurch die Server Abfrage nicht zu lange dauert.
Alternativ bis das Update dazu da ist, kannst du probieren die drei Datenpunktnamen selbst raus zu suchen und in die productGroups.json von der Integration einzutragen. Hier ist eine kurze Anleitung um die Datenpunktnamen zu finden: [Link](https://github.com/Kleinrotti/py-senertec/issues/2#issuecomment-1356823656)

**Comment by MarAlze** [comment]
Leider haben die 3 Speicher temp Fühler kein Label.

Ich glaube ich muss die py-senertec noch einmal in der aktuellen Version herunterladen und einmal ohne Filter laufen lassen um die Datenpunktnamen herauszufinden.

Als Idee für die Erweiterung ggf. Nach einem ersten Scan einen Dialog oder eine Config Seite anzeigen lassen mit allen verfügbaren. Dort sind dann ein paar Standart-Werte ausgewählt. Da kann der Anwender dann selbst auswählen.
