### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by RalfKraemer1** [Kleinrotti/hass-senertec#4]
Hello, I have a Dachs Gen2 G5.5. Logging on to the Dachs2 portal via SSO works.
Unfortunately not with the plugin.
Error message "Login failed, username or password wrong."
Do you have any more ideas about this?
Unfortunately, it does not work with PY-senertec too.

**Comment by Kleinrotti** [comment]
Can you try to login with the demo account from senertec?
Username/email: dachsportal@senertec.com
PW: demo

**Comment by RalfKraemer1** [comment]
That Works. So there might be something with my login...

**Comment by Kleinrotti** [comment]
Do you have any special characters in your password? Maybe a specific character gets not escaped correctly.
If yes, you could change the password to one without special characters for testing purposes.

**Comment by RalfKraemer1** [comment]
Hello, replacing the "%" sign from the Password solves the Problem!
Thank you for the Hint

**Comment by cream68** [comment]
Is there a way to input a password with special characters or do i have to change the password in this case?
