### ISSUE TITLE
Electrical Power value missing

### ISSUE THREAD

**Issue by DieSeef** [Kleinrotti/hass-senertec#7]
I love this integration and it is working great for me! There is only one detail
missing. On the Senertec Dachs Portal the current electrical power (Elektrische Leistung) in kW is visible but this value is not available in the integration. Is there a way to make this available in the integration?

**Comment by Kleinrotti** [comment]
What heating system do you have?

**Comment by DieSeef** [comment]
> What heating system do you have?

It is a Senertec Dachs Gen2 G5.5, installed in 2020

![image](https://github.com/Kleinrotti/hass-senertec/assets/131398023/c8195f8c-7e8b-47eb-a8ec-7acea0ecede2)
The red marked value is what i‘m looking for in the integration.

I want to integrate this value in the energy dashboard ;-)

**Comment by Kleinrotti** [comment]
That should be the datapoint MM000.
You can add it to the productGroups.json file in this section.
![image](https://github.com/Kleinrotti/hass-senertec/assets/39203164/8a87397b-be34-4bee-983c-bfdb7d498c8b)


Keep in mind if you update the intergration, the productGroups.json gets overridden and you have to add that value again.

**Comment by DieSeef** [comment]
> That should be the datapoint MM000. You can add it to the productGroups.json file in this section. ![image](https://user-images.githubusercontent.com/39203164/271578364-8a87397b-be34-4bee-983c-bfdb7d498c8b.png)
> 
> Keep in mind if you update the intergration, the productGroups.json gets overridden and you have to add that value again.

SUPER, it is working and even displayed correctly in the energy dashboard. Thank you very much!

**Comment by Kleinrotti** [comment]
Nice to hear :)
