### ISSUE TITLE
Invalid authentication bei der Einrichtung

### ISSUE THREAD

**Issue by beyondsmarthome** [Kleinrotti/hass-senertec#9]
Die Ersteinrichtung scheitert mit der anzeige Invalid authentication obwohl die Zugangsdaten korrekt sind. Ein Deinstallation und Neuinstallation der Integration durch HACs hat auch nichts gebracht.
Für eine Lösung wäre ich sehr Dankbar. 
Fehlermeldung und Log Ereignis sind angehängt.
Liebe Grüße 

![Bildschirmfoto 2024-02-04 um 18 28 06](https://github.com/Kleinrotti/hass-senertec/assets/53001554/f7957604-e1a0-4f36-a4d1-4ea5509604d1)
![Bildschirmfoto 2024-02-04 um 18 28 51](https://github.com/Kleinrotti/hass-senertec/assets/53001554/7623712f-db68-4788-b858-20420162fe4e)

**Comment by Kleinrotti** [comment]
Could be the same problem described [here](https://github.com/Kleinrotti/hass-senertec/issues/4)

**Comment by beyondsmarthome** [comment]
Thank you very much. It’s now working perfectly.
